INSERT INTO events (slug, title, subtitle, description, agenda, curriculum, learn_items, outcomes, for_you, not_for_you, inside_flow, venue, event_date, price, original_price, value_anchor_price, currency, cover_image, gallery, video_url, cta_label, cta_url, status, featured, max_seats, seats_sold, is_free, delivery_mode, duration_mins, language, timezone, tagline, instructor_note)
VALUES (
'the-money-blueprint',
'THE MONEY BLUEPRINT',
'5 Money Decisions Every Family Should Get Right',
'You earn money. But do you have a money system? Salary comes in. Bills go out. Some money goes into FD, some into insurance, some into SIPs and some stays in the bank. But is everything working together? THE MONEY BLUEPRINT is a practical financial foundation workshop for working individuals and families who want a clear framework for managing, protecting and investing their money. Primary promise: In one practical live session, understand the five money decisions that help you move from simply earning and saving to managing money with purpose.',
'[]',
'[{"title":"Module 1: Money Foundations","lessons":["What is money, income vs wealth","Needs vs wants — budgeting basics","Cash flow: income, expenses, savings","Emergency fund — why and how much"]},
{"title":"Module 2: Understanding Risk & Protection First","lessons":["Why protection comes before investment","Term insurance — the foundation","Health insurance — protecting your savings","Common mistakes: mixing insurance with investment (endowment/ULIP traps)"]},
{"title":"Module 3: The Time Value of Money","lessons":["Inflation — the silent wealth killer","Power of compounding (with real number examples)","Why starting early beats investing more later"]},
{"title":"Module 4: Understanding Investment Options","lessons":["Fixed deposits, gold, real estate — traditional options and their limits","What is a mutual fund — demystified","Equity vs debt — risk and return basics","SIP vs lumpsum — which suits whom"]},
{"title":"Module 5: Goal-Based Investing","lessons":["Setting financial goals (short/medium/long term)","Matching investments to goals (child education, retirement, house)","Asset allocation basics"]},
{"title":"Module 6: Going Deeper","lessons":["Types of mutual funds (large cap, mid cap, hybrid, debt)","Understanding risk profiling","Tax-efficient investing (ELSS, LTCG/STCG basics)","NRI-specific: NRE/NRO, DTAA, repatriation basics"]},
{"title":"Module 7: Advanced/Wealth Stage","lessons":["PMS and AIF — when you outgrow mutual funds","GIFT City — global investment access for NRIs","Retirement corpus planning — building your income machine"]},
{"title":"Module 8: Action","lessons":["How to start — practical first steps","Common behavioral mistakes (panic selling, chasing returns)","Q&A / building your personal financial plan"]}]',
'["01 - Master Your Money - Income, savings, needs/wants, emergency fund","02 - Protect Before You Grow - Term, health insurance, protection gap","03 - Use the Power of Time - Inflation, compounding, cost of delay","04 - Know Where Your Money Belongs - FD, gold, real estate, mutual funds, SIP/lumpsum"]',
'["A simple framework to separate income, savings and wealth creation","A clearer way to think about emergency reserves and protection","A practical understanding of inflation and compounding","A framework for comparing investment categories by purpose, time and risk","A starting point for connecting investments to short-, medium- and long-term goals","A personal checklist of areas that may need review"]',
'["You earn a regular income but do not have a structured financial plan","You invest but are unsure whether everything is properly allocated","You have insurance but are unsure about the adequacy of protection","You have SIPs or FDs without clearly defined goals","You are building wealth for family, education or retirement"]',
'["You want guaranteed returns","You want a stock tip or next multibagger","You want a single investment product to solve everything","You expect a one-size-fits-all portfolio"]',
'["Money structure - Cash flow & emergency","Protection - Term & health shield","Time - Inflation & compounding","Investment choices - Mutual funds, equity/debt, SIP vs lumpsum","Goal-based investing - Align money to goals","Personal Money Check - Live gap scan","Q&A - Build your personal plan + optional Money Clarity Session"]',
'Online - Live on Zoom (link shared on WhatsApp after registration)',
'2026-08-30T13:30:00.000Z',
0,
NULL,
1999,
'INR',
'/images/services-hero.jpg',
'[]',
NULL,
'RESERVE MY FREE SEAT',
NULL,
'published',
1,
200,
147,
1,
'online',
90,
'English',
'Asia/Kolkata',
'Earn. Protect. Grow. Build.',
'Why FREE? This is education-first. We teach the system free - no stock tips, no guaranteed returns, no single-product pitch. If you want us to implement it for you (Mutual Funds / PMS / AIF / GIFT City), you can book a 1:1 Money Clarity Session after - no obligation, education first. Led by Francis J., AMFI-Registered MFD (ARN-335677), 10+ years guiding 100+ families.'
);
